### ISSUE TITLE
Configured theme does not persist between changing story

### ISSUE THREAD

**Issue by ccoyotedev** [jeslage/storybook-addon-theme-playground#19]
Hello there. I am using your addon within my companies style guide to assist the designers.

I was wondering if the theme playground properties are meant to persist between story changes?

Currently, if I edit a theme property and change the page the theme goes back to its default values. However, upon changing a property the theme goes back to the configured version.

Is this working as intended? If not, is there a workaround to have the configured theme persist without the need to toggle a theme value?

(p.s. appreciate all your hard work)

**Comment by jeslage** [comment]
Hey @cgcbrown, 
you are absolutely right, the addon should persist the state on story change, but it currently doesn't. There is currently no workaround to solve this, but this is definitely an enhancement I will work on. I already did some research on how I can achieve a persisted state in a storybook addon and I will try to implement it as soon as possible. I will let you know, when the new release is shipped.

**Comment by jeslage** [comment]
@cgcbrown which version of Storybook are you currently using at your company? I refactored the state handling and removed some custom components in favor of the built in Storybook core components to reduce the bundle size of the addon, but found out that these changes wont work with smaller versions than Storybook v6.

**Comment by ccoyotedev** [comment]
Hey @jeslage,

We are currently using v6.0.22. So we should be all good!

**Comment by jeslage** [comment]
I recently released version 2 of the addon including the fix of this issue. 
It should work out of the box with your current configuration, but there are some major changes coming with the new release which will be deprecated in future releases. If it doesnt work properly you can check out the [migration](https://github.com/jeslage/storybook-addon-theme-playground/tree/master#migration) section in the readme. If you have any issues with the new release, just let me know!
