### ISSUE TITLE
Theme object throws error

### ISSUE THREAD

**Issue by jeslage** [jeslage/storybook-addon-theme-playground#23]
The following theme object throws an error inside the addon.
```
const tokens: Tokens = {
  breakpoints: {
    s: 375,
    m: 768,
    l: 1024
  },
  colors: {
    black: '#181920',
    white: '#fff',
    primary: '#1E41FF',
    secondary: '#eee',
    positive: '#009900',
    critical: '#ff0000'
  },
  grid: {
    columns: 12,
    gutters: 0
  },
  spacings: {
    xs: 5,
    s: 10,
    m: 15,
    l: 20,
    xl: 25
  }
};
```
![Bildschirmfoto 2021-01-21 um 10 24 54](https://user-images.githubusercontent.com/29509730/105330919-1f857880-5bd3-11eb-88cf-942c874b920f.png)

**Comment by samvv** [comment]
Getting the same error. Any idea of what is causing this?

**Comment by samvv** [comment]
I've looked into the code, but I couldn't get the example to work. The `ThemeControls` interface simply doesn't show up in the Storybook. Really unfortunate, because I really love what you've done.

Could you maybe give a bit more information how the example should be configured and run?

**Comment by jeslage** [comment]
@samvv i deployed a new version (2.1.0). This should now fix the missing controls object bug.
Let me know if you have another issue and thanks for contributing!

**Comment by samvv** [comment]
Wow awesome, thanks! 😄 I'm going to use it right away in my project!

Sam
-------- Original Message --------
