### ISSUE TITLE
Storyshots Invalid hook call when using addon-theme-playground

### ISSUE THREAD

**Issue by catkav** [jeslage/storybook-addon-theme-playground#3]
Firstly, this is a great addon, and has been very useful for a color palette update, so thank you! 

I've come across an issue I'm wondering if you could help with, when I'm using addon-theme-playground and I run a Storyshots test suite I get an 'Invalid hook call.' for each story tested, and when I disable addon-theme-playground the tests run ok. 

`  ● Storyshots › App › App Story

    Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
    See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

      at resolveDispatcher (node_modules/react/cjs/react.development.js:1465:13)
      at Object.useState (node_modules/react/cjs/react.development.js:1496:20)
      at node_modules/storybook-addon-theme-playground/dist/src/withThemePlayground.tsx:29:9
      at node_modules/@storybook/addons/dist/hooks.js:241:21
      at node_modules/@storybook/client-api/dist/client_api.js:135:14
      at node_modules/@storybook/client-api/dist/client_api.js:136:16
      at withSubscriptionTracking (node_modules/@storybook/client-api/dist/client_api.js:164:16)
      at node_modules/@storybook/addons/dist/hooks.js:241:21
      at node_modules/@storybook/client-api/dist/client_api.js:135:14
      at node_modules/@storybook/addons/dist/hooks.js:269:20
      at Object.storyFn (node_modules/@storybook/client-api/dist/story_store.js:396:30)
      at getRenderedTree (node_modules/@storybook/addon-storyshots/dist/frameworks/react/renderTree.js:21:30)
      at node_modules/@storybook/addon-storyshots/dist/test-bodies.js:10:22
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/api/snapshotsTestsTemplate.js:42:20)`

I created a little test project to recreate it outside of the large project it's being used in https://github.com/catkav/theme-playground-test

Have you come across anything like this and would you have any ideas for getting around it? The designers I'm working with love this addon so would appreciate any advice!

**Comment by jeslage** [comment]
Thank you, nice to hear that you like the addon! I haven't come across this yet, but let me check your example repo and see if I can track the issue.

**Comment by catkav** [comment]
Thank you, appreciate it, if you need any more information or there's anything I can do to help let me know!

EDIT: Just realised that first test repo has some dependencies that are private, so made a simpler one https://github.com/catkav/theme-playground-test-2

Also it was suggested to try changing 
`return <ThemeProvider theme={currentTheme}>{story()}</ThemeProvider>;`

to:
`return <ThemeProvider theme={currentTheme}><Story /></ThemeProvider>;`

I don't fully understand that but maybe it means something to you.

**Comment by jeslage** [comment]
Sorry for my late response. I found out what caused the "Invalid hook call" issue and updated the `withThemePlayground` component. I tested it with your example repo and all tests where successful. 

I published a new version `1.3.3`, which solves your issue. If there's anything else, just let me know.

**Comment by catkav** [comment]
Amazing, thank you!
