### ISSUE TITLE
React 18 Update

### ISSUE THREAD

**Issue by oliviamallon-eq** [jeslage/storybook-addon-theme-playground#33]
Hi, just wondering if there are going to be plans to make this usable for React 18?

**Comment by jeslage** [comment]
Hi Olivia,

sorry for my late response. Which storybook version are you using? Or do you have an error message where the plugin fails?
Then i can look into it to make it work for React 18 as well.

**Comment by nikk15** [comment]
Seconded! I would love to use this awesome tool but we are also in the process of upgrading to React 18.

**Comment by jeslage** [comment]
@nikk15 i will have a look into this. Which storybook version are you currently running for react 18?

**Comment by nikk15** [comment]
Currently, we are using 6.5.16. But we can upgrade that if needed too. Thank you!

**Comment by nikk15** [comment]
Correction - we just updated Storybook to 7.0.20 today to work in conjunction with React 18. :)

**Comment by jeslage** [comment]
Okay, I started to update the plugin but haven't finished it yet. Storybook 7 changed a lot inside the internal Storybook packages so I have to rewrite the plugin a bit. I will let you know when its finished!

**Comment by oliviamallon-eq** [comment]
Hi, sorry for the late reply, somehow didn't see the message! I am also using version 7.0.2 of storybook

**Comment by thawankeane** [comment]
+1

This is by far the most complete theming addon

@jeslage let us know if you need some help

**Comment by jeslage** [comment]
@thawankeane @nikk15 @oliviamallon-eq i managed to make a new release. You can install version 3.0.0. It depends on a minimum version 7.0.2 of Storybook. If you have any issues with this release just let me know. And thanks for the kind words @thawankeane! :)

**Comment by nikk15** [comment]
@jeslage thank you for your efforts and maintaining an awesome library! 👏

**Comment by jeslage** [comment]
@thawankeane @nikk15 @oliviamallon-eq sorry I had some issues while releasing, because I added semantic-release via GitHub action and it didn't work properly yet. This should have been a major release due to breaking changes in the code and related packages. 
I released a new version 3.0.0 and will delete the 2.3.0 release if possible. So please update directly to version 3.0.0.
Sorry for the mistake, new to this whole GitHub action auto releasing stuff :D

**Comment by jeslage** [comment]
Had some issues with vite as builder. If you come across the same issue you can try updating to 3.0.2.

**Comment by oliviamallon-eq** [comment]
Thank you so much!
