### ISSUE TITLE
Fails to import `lodash` with Yarn 2 

### ISSUE THREAD

**Issue by seamusleahy** [jeslage/storybook-addon-theme-playground#6]
Lodash is imported in [`src/helper/index.ts`](https://github.com/jeslage/storybook-addon-theme-playground/blob/6479d79ea94c80db36d26319f792dfbab2413f2c/src/helper/index.ts#L1) but it is not included in the dependences. This doesn't cause an issue with Yarn 1 because Lodash is in `node_modules` thanks to being in the dependences tree of Storybook. With Yarn 2's plug-and-play (PNP), the way modules are managed changed. Yarn 2 will not provide an undeclared module to a module even when it likely has it.

> Module not found: Error: storybook-addon-theme-playground tried to access lodash, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

The fix I believe is to declare Lodash in the dependencies.

**Comment by jeslage** [comment]
Thanks for the issue. I added `lodash.startcase` instead of the whole `lodash` dependency  to the dependency list and updated `src/helper/index.ts`. I recently published a new version which should solve your issue. Update to version `1.3.2`.
